version: '3.8'
services:
  movies:
    image: vaishu111/moviesservice:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: vaishu111/trainservice:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: vaishu111/dthservice:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: vaishu111/rechargeservice:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
